CREATE DATABASE EST_CASO_III_DDL;

USE EST_CASO_III_DDL;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_ID INT PRIMARY KEY NOT NULL,
PAG_TOTAL DECIMAL (10,2) NOT NULL,
PAG_DESCONTO DECIMAL(10,2),
PAG_LIQUIDO DECIMAL (10,2) NOT NULL,
PAG_FORMA VARCHAR(20) NOT NULL,
PAG_QTPARCELAS INT NOT NULL
);

ALTER TABLE PAGAMENTOS ADD PAG_HISTORICO VARCHAR(100);
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_HISTORICO TEXT;
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_HISTORICO PAG_HIST TEXT;
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_HIST;

CREATE TABLE IF NOT EXISTS TIPOS_DE_COMPONENTES(
TDC_COD INT PRIMARY KEY NOT NULL,
TDC_NOME VARCHAR(100) NOT NULL
);

ALTER TABLE TIPOS_DE_COMPONENTES ADD TDC_QUANTIDADE VARCHAR(100);
ALTER TABLE TIPOS_DE_COMPONENTES MODIFY COLUMN TDC_QUANTIDADE INT;
ALTER TABLE TIPOS_DE_COMPONENTES CHANGE COLUMN TDC_QUANTIDADE TDC_QT INT;
ALTER TABLE TIPOS_DE_COMPONENTES DROP COLUMN TDC_QT;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_CPNJ VARCHAR(20) PRIMARY KEY NOT NULL,
FORN_RAZAOSOCIAL TEXT NOT NULL,
FORN_PESSOACONTATO VARCHAR(20) NOT NULL
);

ALTER TABLE FORNECEDORES ADD FORNEC_EMAIL VARCHAR(100);
ALTER TABLE FORNECEDORES MODIFY COLUMN FORNEC_EMAIL VARCHAR(150);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORNEC_EMAIL EMAIL_FORNEC VARCHAR(150);
ALTER TABLE FORNECEDORES DROP COLUMN EMAIL_FORNEC;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLI_COD INT PRIMARY KEY NOT NULL,
CLI_CNPJ VARCHAR(20) NOT NULL,
CLI_RAZAOSOCIAL TEXT NOT NULL,
CLI_RAMOATV VARCHAR (50) NOT NULL,
CLI_DATACASDASTRO DATETIME NOT NULL,
CLI_PESSOACONTATO VARCHAR(20)
);

ALTER TABLE CLIENTES ADD CLI_EMAIL VARCHAR(100);
ALTER TABLE CLIENTES MODIFY COLUMN CLI_EMAIL VARCHAR(150);
ALTER TABLE CLIENTES CHANGE COLUMN CLI_EMAIL EMAIL_CLI VARCHAR(150);
ALTER TABLE CLIENTES DROP COLUMN EMAIL_CLI;

CREATE TABLE IF NOT EXISTS EMPREGADOS(
EMP_MATR INT PRIMARY KEY NOT NULL,
EMP_NOME VARCHAR(50) NOT NULL,
EMP_CARGO VARCHAR(50) NOT NULL,
EMP_SALARIO DECIMAL (10,2) NOT NULL,
EMP_DATAADI DATE NOT NULL,
EMP_QUALIFICACOES TEXT NOT NULL
);

ALTER TABLE EMPREGADOS ADD EMP_DINHEIRO_DEVENDO INT;
ALTER TABLE EMPREGADOS MODIFY COLUMN EMP_DINHEIRO_DEVENDO DECIMAL(10,2);
ALTER TABLE EMPREGADOS CHANGE COLUMN EMP_DINHEIRO_DEVENDO EMP_DIVIDA DECIMAL(10,2);
ALTER TABLE EMPREGADOS DROP COLUMN EMP_DIVIDA;

CREATE TABLE IF NOT EXISTS MAQUINAS(
MAQ_COD INT PRIMARY KEY NOT NULL,
MAQ_FIMGARANTIA DATE NOT NULL,
MAQ_DATACOMPRA DATETIME NOT NULL,
MAQ_TEMPODEVIDA DATE NOT NULL
);

ALTER TABLE MAQUINAS ADD MAQ_STATUS VARCHAR(100);
ALTER TABLE MAQUINAS MODIFY COLUMN MAQ_STATUS TEXT;
ALTER TABLE MAQUINAS CHANGE COLUMN MAQ_STATUS MAQ_ST TEXT;
ALTER TABLE MAQUINAS DROP COLUMN MAQ_ST;

CREATE TABLE IF NOT EXISTS TABELACOMDROP(
TABELADROP_COD INT PRIMARY KEY NOT NULL
);

ALTER TABLE TABELACOMDROP ADD TABELADROP_NOME INT;
ALTER TABLE TABELACOMDROP MODIFY COLUMN TABELADROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP CHANGE COLUMN TABELADROP_NOME TBDROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP DROP COLUMN TBDROP_NOME;
DROP TABLE TABELACOMDROP;

CREATE TABLE IF NOT EXISTS COMPONENTES(
COMP_COD INT PRIMARY KEY NOT NULL,
COMP_NOME VARCHAR(100) NOT NULL,
COMP_QT_ESTOQUE INT,
COMP_PRECO_UNIT DECIMAL(10,2) NOT NULL,
COMP_UND VARCHAR(15) NOT NULL,
COMP_TDC_COD INT NOT NULL,
CONSTRAINT FK_COMP_TDC_COD FOREIGN KEY (COMP_TDC_COD) REFERENCES TIPOS_DE_COMPONENTES(TDC_COD)
);

ALTER TABLE COMPONENTES ADD COMP_STATUS VARCHAR(100);
ALTER TABLE COMPONENTES MODIFY COLUMN COMP_STATUS TEXT;
ALTER TABLE COMPONENTES CHANGE COLUMN COMP_STATUS COMP_ST TEXT;
ALTER TABLE COMPONENTES DROP COLUMN COMP_ST;

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
ENC_NUM INT PRIMARY KEY NOT NULL,
ENC_DATAINCLU DATETIME NOT NULL,
ENC_PAG_ID INT NOT NULL,
ENC_CLI_COD INT NOT NULL,
CONSTRAINT FK_ENC_PAG_ID FOREIGN KEY (ENC_PAG_ID) REFERENCES PAGAMENTOS(PAG_ID),
CONSTRAINT FK_ENC_CLI_COD FOREIGN KEY (ENC_CLI_COD) REFERENCES CLIENTES(CLI_COD)
);

ALTER TABLE ENCOMENDAS ADD ENC_STATUS VARCHAR(100);
ALTER TABLE ENCOMENDAS MODIFY COLUMN ENC_STATUS TEXT;
ALTER TABLE ENCOMENDAS CHANGE COLUMN ENC_STATUS ENC_ST TEXT;
ALTER TABLE ENCOMENDAS DROP COLUMN ENC_ST;

CREATE TABLE IF NOT EXISTS TIPOS_DE_ENDERECOS(
TDE_COD INT PRIMARY KEY NOT NULL,
TDE_NOME VARCHAR(50) NOT NULL,
TDE_FORN_CPNJ VARCHAR(20) NOT NULL,
TDE_CLI_COD INT NOT NULL,
TDE_EMP_MATR INT NOT NULL,
CONSTRAINT FK_TDE_FORN_CPNJ FOREIGN KEY (TDE_FORN_CPNJ) REFERENCES FORNECEDORES(FORN_CPNJ),
CONSTRAINT FK_TDE_CLI_COD FOREIGN KEY (TDE_CLI_COD) REFERENCES CLIENTES(CLI_COD),
CONSTRAINT FK_TDE_EMP_MATR FOREIGN KEY (TDE_EMP_MATR) REFERENCES EMPREGADOS(EMP_MATR)
);

ALTER TABLE TIPOS_DE_ENDERECOS ADD TDE_QUANTIDADE VARCHAR(100);
ALTER TABLE TIPOS_DE_ENDERECOS MODIFY COLUMN TDE_QUANTIDADE INT;
ALTER TABLE TIPOS_DE_ENDERECOS CHANGE COLUMN TDE_QUANTIDADE TDE_QT INT;
ALTER TABLE TIPOS_DE_ENDERECOS DROP COLUMN TDE_QT;

CREATE TABLE IF NOT EXISTS ENDERECOS(
ENDE_LOG VARCHAR(50) NOT NULL,
ENDE_NUM INT,
ENDE_COMPLE VARCHAR(50),
ENDE_BAIRRO VARCHAR(50),
ENDE_CIDADE VARCHAR(50),
ENDE_UF VARCHAR(2),
ENDE_PAIS VARCHAR(50) NOT NULL,
ENDE_CEP VARCHAR(10),
ENDE_TDE_FORN_CPNJ VARCHAR(20) NOT NULL,
ENDE_TDE_CLI_COD INT NOT NULL,
ENDE_TDE_EMP_MATR INT NOT NULL,
CONSTRAINT FK_ENDE_TDE_FORN_CPNJ FOREIGN KEY (ENDE_TDE_FORN_CPNJ) REFERENCES TIPOS_DE_ENDERECOS (TDE_FORN_CPNJ),
CONSTRAINT FK_ENDE_TDE_CLI_COD FOREIGN KEY (ENDE_TDE_CLI_COD) REFERENCES TIPOS_DE_ENDERECOS (TDE_CLI_COD),
CONSTRAINT FK_ENDE_TDE_EMP_MATR FOREIGN KEY (ENDE_TDE_EMP_MATR) REFERENCES TIPOS_DE_ENDERECOS (TDE_EMP_MATR)
);

ALTER TABLE ENDERECOS ADD ENDE_QUANTIDADE VARCHAR(100);
ALTER TABLE ENDERECOS MODIFY COLUMN ENDE_QUANTIDADE INT;
ALTER TABLE ENDERECOS CHANGE COLUMN ENDE_QUANTIDADE ENDE_QT INT;
ALTER TABLE ENDERECOS DROP COLUMN ENDE_QT;

CREATE TABLE IF NOT EXISTS TELEFONES(
TELE_DDI VARCHAR(4) NOT NULL,
TELE_DDD INT NOT NULL,
TELE_NUM VARCHAR(9) NOT NULL,
TELE_FORN_CPNJ VARCHAR(20) NOT NULL,
TELE_CLI_COD INT NOT NULL,
TELE_EMP_MATR INT NOT NULL,
CONSTRAINT FK_TELE_FORN_CPNJ FOREIGN KEY (TELE_FORN_CPNJ) REFERENCES FORNECEDORES(FORN_CPNJ),
CONSTRAINT FK_TELE_CLI_COD FOREIGN KEY (TELE_CLI_COD) REFERENCES CLIENTES(CLI_COD),
CONSTRAINT FK_TELE_EMP_MATR FOREIGN KEY (TELE_EMP_MATR) REFERENCES EMPREGADOS(EMP_MATR)
);

ALTER TABLE TELEFONES ADD TELE_QUANTIDADE VARCHAR(100);
ALTER TABLE TELEFONES MODIFY COLUMN TELE_QUANTIDADE INT;
ALTER TABLE TELEFONES CHANGE COLUMN TELE_QUANTIDADE TELE_QT INT;
ALTER TABLE TELEFONES DROP COLUMN TELE_QT;

CREATE TABLE IF NOT EXISTS REGISTRO_DE_MANUTENCAO(
RM_DATA DATE NOT NULL,
RM_DESCRICAO TEXT NOT NULL,
RM_MAQ_COD INT NOT NULL,
CONSTRAINT FK_RM_MAQ_COD FOREIGN KEY (RM_MAQ_COD) REFERENCES MAQUINAS(MAQ_COD)
);

ALTER TABLE REGISTRO_DE_MANUTENCAO ADD RM_STATUS VARCHAR(100);
ALTER TABLE REGISTRO_DE_MANUTENCAO MODIFY COLUMN RM_STATUS TEXT;
ALTER TABLE REGISTRO_DE_MANUTENCAO CHANGE COLUMN RM_STATUS RM_ST TEXT;
ALTER TABLE REGISTRO_DE_MANUTENCAO DROP COLUMN RM_ST;

CREATE TABLE IF NOT EXISTS COMPONENTES_FORNECEDORES(
CMFR_COMP_COD INT NOT NULL,
CMFR_FORN_CPNJ VARCHAR(20) NOT NULL,
PRIMARY KEY(CMFR_COMP_COD, CMFR_FORN_CPNJ),
CONSTRAINT CMFR_PKFK_COMP_COD FOREIGN KEY (CMFR_COMP_COD) REFERENCES COMPONENTES(COMP_COD),
CONSTRAINT CMFR_PKFK_FORN_CPNJ FOREIGN KEY (CMFR_FORN_CPNJ) REFERENCES FORNECEDORES(FORN_CPNJ)
);

ALTER TABLE COMPONENTES_FORNECEDORES ADD CMFR_COMP_STATUS VARCHAR(100);
ALTER TABLE COMPONENTES_FORNECEDORES MODIFY COLUMN CMFR_COMP_STATUS TEXT;
ALTER TABLE COMPONENTES_FORNECEDORES CHANGE COLUMN CMFR_COMP_STATUS CMFR_COMP_ST TEXT;
ALTER TABLE COMPONENTES_FORNECEDORES DROP COLUMN CMFR_COMP_ST;

CREATE TABLE IF NOT EXISTS REGISTRO_DE_SUPRIMENTO(
RS_COMP_COD INT NOT NULL,
RS_MAQ_COD INT NOT NULL,
PRIMARY KEY(RS_COMP_COD, RS_MAQ_COD),
RS_QNT INT,
RS_DATANECESSIDADE DATE NOT NULL,
CONSTRAINT RS_PKFK_COMP_COD FOREIGN KEY (RS_COMP_COD) REFERENCES COMPONENTES(COMP_COD),
CONSTRAINT RS_PKFK_MAQ_COD FOREIGN KEY (RS_MAQ_COD) REFERENCES MAQUINAS(MAQ_COD)
);

ALTER TABLE REGISTRO_DE_SUPRIMENTO ADD RS_COMP_STATUS VARCHAR(100);
ALTER TABLE REGISTRO_DE_SUPRIMENTO MODIFY COLUMN RS_COMP_STATUS TEXT;
ALTER TABLE REGISTRO_DE_SUPRIMENTO CHANGE COLUMN RS_COMP_STATUS RS_COMP_ST TEXT;
ALTER TABLE REGISTRO_DE_SUPRIMENTO DROP COLUMN RS_COMP_ST;

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY NOT NULL,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_COR VARCHAR(20) NOT NULL,
PROD_DIMENSOES VARCHAR(50) NOT NULL,
PROD_PESO DECIMAL (10,3) NOT NULL,
PROD_TEMPFAB TIME NOT NULL,
PROD_HORAOBRA TIME NOT NULL,
PROD_DESENHO BLOB NOT NULL,
PROD_ENC_NUM INT NOT NULL,
PROD_EMP_MATR INT NOT NULL,
PROD_RS_COMP_COD INT NOT NULL,
PROD_RS_MAQ_COD INT NOT NULL,
CONSTRAINT FK_PROD_ENC_NUM FOREIGN KEY (PROD_ENC_NUM) REFERENCES ENCOMENDAS(ENC_NUM),
CONSTRAINT FK_PROD_EMP_MATR FOREIGN KEY (PROD_EMP_MATR) REFERENCES EMPREGADOS(EMP_MATR),
CONSTRAINT FK_PROD_RS_COMP_COD FOREIGN KEY (PROD_RS_COMP_COD) REFERENCES REGISTRO_DE_SUPRIMENTO(RS_COMP_COD),
CONSTRAINT FK_PROD_RS_MAQ_COD FOREIGN KEY (PROD_RS_MAQ_COD) REFERENCES REGISTRO_DE_SUPRIMENTO(RS_MAQ_COD)
);

ALTER TABLE PRODUTOS ADD PROD_QUANTIDADE VARCHAR(100);
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_QUANTIDADE INT;
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_QUANTIDADE PROD_QT INT;
ALTER TABLE PRODUTOS DROP COLUMN PROD_QT;
