CREATE DATABASE EST_CASO_II_DDL;

USE EST_CASO_II_DDL;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(20) PRIMARY KEY NOT NULL,
PASS_NOME VARCHAR(100) NOT NULL,
PASS_EMAIL VARCHAR(50) NOT NULL,
PASS_TELEFONE VARCHAR(20) NOT NULL,
PASS_RUA VARCHAR(100) NOT NULL,
PASS_NUMRUA INT,
PAS_BAIRRO VARCHAR(100) NOT NULL,
PASS_CIDADE VARCHAR(100) NOT NULL,
PASS_ESTADO VARCHAR(50) NOT NULL,
PASS_PAIS VARCHAR(50) NOT NULL,
PASS_CODPOSTAL VARCHAR(10) NOT NULL
);

ALTER TABLE PASSAGEIROS ADD PASS_HISTORICO VARCHAR(100);
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_HISTORICO TEXT;
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_HISTORICO PASS_HIST TEXT;
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_HIST;

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD VARCHAR(30) PRIMARY KEY NOT NULL,
AEROP_NOME VARCHAR(100) NOT NULL,
AEROP_CIDADE VARCHAR(100) NOT NULL,
AEROP_PAIS VARCHAR(50) NOT NULL,
AEROP_LATITUDE DECIMAL(10,8),
AEROP_LONGITUDE DECIMAL(11,8)
);

ALTER TABLE AEROPORTOS ADD AEROP_CAPACIDADE VARCHAR(100);
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_CAPACIDADE INT;
ALTER TABLE AEROPORTOS CHANGE COLUMN AEROP_CAPACIDADE AEROP_CAPAC INT;
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_CAPAC;

CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO VARCHAR(50) PRIMARY KEY NOT NULL,
AERON_MODELO VARCHAR(50) NOT NULL,
AERON_ANOFABR YEAR NOT NULL,
AERON_AUTONOMIA DECIMAL(4,2) NOT NULL,
AERON_CAPACIDADE INT NOT NULL,
AERON_FABRICANTE VARCHAR(50) NOT NULL
);

ALTER TABLE AERONAVES ADD AERON_HISTORICO VARCHAR(100);
ALTER TABLE AERONAVES MODIFY COLUMN AERON_HISTORICO TEXT;
ALTER TABLE AERONAVES CHANGE COLUMN AERON_HISTORICO AERON_HIST TEXT;
ALTER TABLE AERONAVES DROP COLUMN AERON_HIST;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY NOT NULL,
FUNC_NOME VARCHAR(100) NOT NULL,
FUNC_DATANASC DATETIME NOT NULL,
FUNC_CPF VARCHAR(20) NOT NULL,
FUNC_FUNCAO TEXT NOT NULL,
FUNC_RUA VARCHAR(100) NOT NULL,
FUNC_NUMRUA INT,
FUNC_BAIRRO VARCHAR(100) NOT NULL,
FUNC_CIDADE VARCHAR(100) NOT NULL,
FUNC_ESTADO VARCHAR(50) NOT NULL,
FUNC_PAIS VARCHAR(50) NOT NULL,
FUNC_CODPOSTAL VARCHAR(10) NOT NULL
);

ALTER TABLE FUNCIONARIOS ADD FUNC_DINHEIRO_DEVENDO INT;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_DINHEIRO_DEVENDO DECIMAL(10,2);
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_DINHEIRO_DEVENDO FUNC_DIVIDA DECIMAL(10,2);
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_DIVIDA;

CREATE TABLE IF NOT EXISTS TABELACOMDROP(
TABELADROP_COD INT PRIMARY KEY NOT NULL
);

ALTER TABLE TABELACOMDROP ADD TABELADROP_NOME INT;
ALTER TABLE TABELACOMDROP MODIFY COLUMN TABELADROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP CHANGE COLUMN TABELADROP_NOME TBDROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP DROP COLUMN TBDROP_NOME;
DROP TABLE TABELACOMDROP;

CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY NOT NULL,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM VARCHAR(30) NOT NULL,
VOO_AEROP_DESTINO VARCHAR(30) NOT NULL,
VOO_AERONAVES VARCHAR(50) NOT NULL,
CONSTRAINT FK_VOOS_AEROPORTOS_ORI FOREIGN KEY (VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT FK_VOOS_AEROPORTOS_DES FOREIGN KEY (VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT FK_VOOS_AERONAVES FOREIGN KEY (VOO_AERONAVES) REFERENCES AERONAVES(AERON_PREFIXO)
);

ALTER TABLE VOOS ADD VOO_PREDIOS_ATINGIDOS VARCHAR(100);
ALTER TABLE VOOS MODIFY COLUMN VOO_PREDIOS_ATINGIDOS INT;
ALTER TABLE VOOS CHANGE COLUMN VOO_PREDIOS_ATINGIDOS VOO_ACIDENTES INT;
ALTER TABLE VOOS DROP COLUMN VOO_ACIDENTES;

CREATE TABLE IF NOT EXISTS RESERVAS(
RES_COD INT PRIMARY KEY NOT NULL,
PASS_CPF VARCHAR(20) NOT NULL,
VOO_ID INT NOT NULL,
CONSTRAINT FK_RESERVAS_PASSAGEIROS FOREIGN KEY (PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT FK_RESERVAS_VOOS FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

ALTER TABLE RESERVAS ADD RES_QUANTIDADE VARCHAR(100);
ALTER TABLE RESERVAS MODIFY COLUMN RES_QUANTIDADE INT;
ALTER TABLE RESERVAS CHANGE COLUMN RES_QUANTIDADE RES_QT INT;
ALTER TABLE RESERVAS DROP COLUMN RES_QT;

CREATE TABLE IF NOT EXISTS OPERACAO_DE_VOO(
FUNC_ID INT NOT NULL,
VOO_ID INT NOT NULL,
PRIMARY KEY (FUNC_ID, VOO_ID),
CONSTRAINT OPV_PKFK_FUNCIONARIOS FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT OPV_PKFK_VOOS FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

ALTER TABLE OPERACAO_DE_VOO ADD OPV_QUANTIDADE VARCHAR(100);
ALTER TABLE OPERACAO_DE_VOO MODIFY COLUMN OPV_QUANTIDADE INT;
ALTER TABLE OPERACAO_DE_VOO CHANGE COLUMN OPV_QUANTIDADE OPV_QT INT;
ALTER TABLE OPERACAO_DE_VOO DROP COLUMN OPV_QT;
