CREATE SCHEMA EST_CASO_I_DDL;

USE EST_CASO_I_DDL;


CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

ALTER TABLE FORNECEDORES ADD FORNEC_EMAIL VARCHAR(100);
ALTER TABLE FORNECEDORES MODIFY COLUMN FORNEC_EMAIL VARCHAR(150);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORNEC_EMAIL EMAIL_FORNEC VARCHAR(150);
ALTER TABLE FORNECEDORES DROP COLUMN EMAIL_FORNEC;

CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL);

ALTER TABLE FILIAIS ADD FILIAL_EMAIL VARCHAR(100);
ALTER TABLE FILIAIS MODIFY COLUMN FILIAL_EMAIL VARCHAR(150);
ALTER TABLE FILIAIS CHANGE COLUMN FILIAL_EMAIL EMAIL_FILIAL VARCHAR(150);
ALTER TABLE FILIAIS DROP COLUMN EMAIL_FILIAL;

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

ALTER TABLE PRODUTOS ADD PROD_PAIS_DE_ORIGEM VARCHAR(100);
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_PAIS_DE_ORIGEM VARCHAR(150);
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_PAIS_DE_ORIGEM PROD_ORIGEM VARCHAR(150);
ALTER TABLE PRODUTOS DROP COLUMN PROD_ORIGEM;

CREATE TABLE IF NOT EXISTS TABELACOMDROP(
TABELADROP_COD INT PRIMARY KEY NOT NULL
);

ALTER TABLE TABELACOMDROP ADD TABELADROP_NOME INT;
ALTER TABLE TABELACOMDROP MODIFY COLUMN TABELADROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP CHANGE COLUMN TABELADROP_NOME TBDROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP DROP COLUMN TBDROP_NOME;
DROP TABLE TABELACOMDROP;

CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_COD)
);

ALTER TABLE PEDIDOS ADD PED_PAIS_DE_ORIGEM VARCHAR(100);
ALTER TABLE PEDIDOS MODIFY COLUMN PED_PAIS_DE_ORIGEM VARCHAR(150);
ALTER TABLE PEDIDOS CHANGE COLUMN PED_PAIS_DE_ORIGEM PED_ORIGEM VARCHAR(150);
ALTER TABLE PEDIDOS DROP COLUMN PED_ORIGEM;

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT NOT NULL,
PRIMARY KEY(RECEB_PEDIDOS),
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO)
);

ALTER TABLE RECEBIMENTOS ADD RECEB_ENTREGADOR VARCHAR(50);
ALTER TABLE RECEBIMENTOS MODIFY COLUMN RECEB_ENTREGADOR VARCHAR(100);
ALTER TABLE RECEBIMENTOS CHANGE COLUMN RECEB_ENTREGADOR RECEB_ENTRE VARCHAR(150);
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEB_ENTRE;

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE PEDIDOS_PRODUTOS ADD PDPR_STATUS VARCHAR(200);
ALTER TABLE PEDIDOS_PRODUTOS MODIFY COLUMN PDPR_STATUS TEXT;
ALTER TABLE PEDIDOS_PRODUTOS CHANGE COLUMN PDPR_STATUS PDPR_STA TEXT;
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN PDPR_STA;

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FILIAIS_PRODUTOS ADD FLPR_STATUS VARCHAR(200);
ALTER TABLE FILIAIS_PRODUTOS MODIFY COLUMN FLPR_STATUS TEXT;
ALTER TABLE FILIAIS_PRODUTOS CHANGE COLUMN FLPR_STATUS FLPR_STA TEXT;
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN FLPR_STA;

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FORNECEDORES_PRODUTOS ADD FRPR_STATUS VARCHAR(200);
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY COLUMN FRPR_STATUS TEXT;
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE COLUMN FRPR_STATUS FRPR_STA TEXT;
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN FRPR_STA;
