CREATE DATABASE EST_CASO_V_DDL;

USE EST_CASO_V_DDL;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLI_CPF VARCHAR(20) PRIMARY KEY NOT NULL,
CLI_NOME VARCHAR(100) NOT NULL,
CLI_DATANASC DATE NOT NULL,
CLI_RUA VARCHAR(50) NOT NULL,
CLI_NUMRUA INT,
CLI_BAIRRO VARCHAR(50) NOT NULL,
CLI_CIDADE VARCHAR(50) NOT NULL,
CLI_UF VARCHAR(2) NOT NULL,
CLI_PAIS VARCHAR(50) NOT NULL,
CLI_CEP VARCHAR(20) NOT NULL,
CLI_STATUS TEXT NOT NULL
);

ALTER TABLE CLIENTES ADD CLI_EMAIL VARCHAR(100);
ALTER TABLE CLIENTES MODIFY COLUMN CLI_EMAIL VARCHAR(150);
ALTER TABLE CLIENTES CHANGE COLUMN CLI_EMAIL EMAIL_CLI VARCHAR(150);
ALTER TABLE CLIENTES DROP COLUMN EMAIL_CLI;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_CNPJ INT PRIMARY KEY NOT NULL,
FORN_CONTATO VARCHAR(20) NOT NULL,
FORN_NOME VARCHAR(100) NOT NULL
);

ALTER TABLE FORNECEDORES ADD FORN_EMAIL VARCHAR(100);
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_EMAIL VARCHAR(150);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_EMAIL EMAIL_FORN VARCHAR(150);
ALTER TABLE FORNECEDORES DROP COLUMN EMAIL_FORN;

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY NOT NULL,
PROD_CATEGORIA VARCHAR(50) NOT NULL,
PROD_PROCO DECIMAL(10,2) NOT NULL,
PROD_QT INT
);

ALTER TABLE PRODUTOS ADD PROD_STATUS VARCHAR(100);
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_STATUS TEXT;
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_STATUS PROD_ST TEXT;
ALTER TABLE PRODUTOS DROP COLUMN PROD_ST;

CREATE TABLE IF NOT EXISTS TABELACOMDROP(
TABELADROP_COD INT PRIMARY KEY NOT NULL
);

ALTER TABLE TABELACOMDROP ADD TABELADROP_NOME INT;
ALTER TABLE TABELACOMDROP MODIFY COLUMN TABELADROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP CHANGE COLUMN TABELADROP_NOME TBDROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP DROP COLUMN TBDROP_NOME;
DROP TABLE TABELACOMDROP;

CREATE TABLE IF NOT EXISTS VENDAS(
VEN_COD INT PRIMARY KEY NOT NULL,
VEN_CLI_CPF VARCHAR(20) NOT NULL,
CONSTRAINT FK_VEN_CLI_CPF FOREIGN KEY (VEN_CLI_CPF) REFERENCES CLIENTES(CLI_CPF)
);

ALTER TABLE VENDAS ADD VEN_HISTORICO VARCHAR(100);
ALTER TABLE VENDAS MODIFY COLUMN VEN_HISTORICO TEXT;
ALTER TABLE VENDAS CHANGE COLUMN VEN_HISTORICO VEN_HIST TEXT;
ALTER TABLE VENDAS DROP COLUMN VEN_HIST;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_CON INT PRIMARY KEY NOT NULL,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS TEXT NOT NULL,
PAG_FORMA VARCHAR(20) NOT NULL,
PAG_VEN_COD INT NOT NULL,
CONSTRAINT FK_PAG_VEN_COD FOREIGN KEY (PAG_VEN_COD) REFERENCES VENDAS(VEN_COD)
);

ALTER TABLE PAGAMENTOS ADD PAG_HISTORICO VARCHAR(100);
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_HISTORICO TEXT;
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_HISTORICO PAG_HIST TEXT;
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_HIST;

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORN_CNPJ INT NOT NULL,
FRPR_PROD_COD INT NOT NULL,
PRIMARY KEY(FRPR_FORN_CNPJ, FRPR_PROD_COD),
CONSTRAINT PKFK_FRPR_FORN_CNPJ FOREIGN KEY (FRPR_FORN_CNPJ) REFERENCES FORNECEDORES(FORN_CNPJ),
CONSTRAINT PKFK_FRPR_PROD_COD FOREIGN KEY (FRPR_PROD_COD) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FORNECEDORES_PRODUTOS ADD FRPR_FORN_HISTORICO VARCHAR(100);
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY COLUMN FRPR_FORN_HISTORICO TEXT;
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE COLUMN FRPR_FORN_HISTORICO FRPR_FORN_HIST TEXT;
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN FRPR_FORN_HIST;

CREATE TABLE IF NOT EXISTS PRODUTOS_VENDAS(
PRVN_PROD_COD INT NOT NULL,
PRVN_VEN_COD INT NOT NULL,
PRIMARY KEY(PRVN_PROD_COD, PRVN_VEN_COD),
PRVN_QT INT NOT NULL,
PRVN_VALOR_VENDA DECIMAL(10,2) NOT NULL,
CONSTRAINT PKFK_PRVN_PROD_COD FOREIGN KEY (PRVN_PROD_COD) REFERENCES PRODUTOS(PROD_COD),
CONSTRAINT PKFK_PRVN_VEN_COD FOREIGN KEY (PRVN_VEN_COD) REFERENCES VENDAS(VEN_COD)
);

ALTER TABLE PRODUTOS_VENDAS ADD PRVN_PROD_HISTORICO VARCHAR(100);
ALTER TABLE PRODUTOS_VENDAS MODIFY COLUMN PRVN_PROD_HISTORICO TEXT;
ALTER TABLE PRODUTOS_VENDAS CHANGE COLUMN PRVN_PROD_HISTORICO PRVN_PROD_HIST TEXT;
ALTER TABLE PRODUTOS_VENDAS DROP COLUMN PRVN_PROD_HIST;
