CREATE DATABASE EST_CASO_IV_DDL;

USE EST_CASO_IV_DDL;

CREATE TABLE IF NOT EXISTS ALUNOS(
ALU_ID INT PRIMARY KEY NOT NULL,
ALU_NOME VARCHAR(100) NOT NULL,
ALU_DATANASC DATE NOT NULL,
ALU_LOG VARCHAR(50) NOT NULL,
ALU_N_LOG INT,
ALU_BAIRRO VARCHAR(50) NOT NULL,
ALU_CIDADE VARCHAR(50) NOT NULL,
ALU_UF VARCHAR(2) NOT NULL,
ALU_PAIS VARCHAR(50) NOT NULL,
ALU_CEP VARCHAR(10) NOT NULL,
ALU_MODAL_PREF VARCHAR(20) NOT NULL
);

ALTER TABLE ALUNOS ADD ALU_EMAIL VARCHAR(100);
ALTER TABLE ALUNOS MODIFY COLUMN ALU_EMAIL VARCHAR(150);
ALTER TABLE ALUNOS CHANGE COLUMN ALU_EMAIL EMAIL_ALU VARCHAR(150);
ALTER TABLE ALUNOS DROP COLUMN EMAIL_ALU;

CREATE TABLE IF NOT EXISTS INSTRUTORES(
INSTRU_ID INT PRIMARY KEY NOT NULL,
INSTRU_NOME VARCHAR(100) NOT NULL
);

ALTER TABLE INSTRUTORES ADD INSTRU_EMAIL VARCHAR(100);
ALTER TABLE INSTRUTORES MODIFY COLUMN INSTRU_EMAIL VARCHAR(150);
ALTER TABLE INSTRUTORES CHANGE COLUMN INSTRU_EMAIL EMAIL_INSTRU VARCHAR(150);
ALTER TABLE INSTRUTORES DROP COLUMN EMAIL_INSTRU;

CREATE TABLE IF NOT EXISTS MODALIDADES(
MODAL_ID INT PRIMARY KEY NOT NULL,
MODAL_NOME VARCHAR(100) NOT NULL
);

ALTER TABLE MODALIDADES ADD MODAL_QUANTIDADE VARCHAR(100);
ALTER TABLE MODALIDADES MODIFY COLUMN MODAL_QUANTIDADE INT;
ALTER TABLE MODALIDADES CHANGE COLUMN MODAL_QUANTIDADE MODAL_QT INT;
ALTER TABLE MODALIDADES DROP COLUMN MODAL_QT;

CREATE TABLE IF NOT EXISTS TABELACOMDROP(
TABELADROP_COD INT PRIMARY KEY NOT NULL
);

ALTER TABLE TABELACOMDROP ADD TABELADROP_NOME INT;
ALTER TABLE TABELACOMDROP MODIFY COLUMN TABELADROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP CHANGE COLUMN TABELADROP_NOME TBDROP_NOME VARCHAR(100);
ALTER TABLE TABELACOMDROP DROP COLUMN TBDROP_NOME;
DROP TABLE TABELACOMDROP;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_ID INT PRIMARY KEY NOT NULL,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS VARCHAR(100) NOT NULL,
PAG_ALU_ID INT NOT NULL,
CONSTRAINT FK_PAG_ALU_ID FOREIGN KEY (PAG_ALU_ID) REFERENCES ALUNOS(ALU_ID)
);

ALTER TABLE PAGAMENTOS ADD PAG_HISTORICO VARCHAR(100);
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_HISTORICO TEXT;
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_HISTORICO PAG_HIST TEXT;
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_HIST;

CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADES(
NSMD_INSTRU_ID INT NOT NULL,
NSMD_MODAL_ID INT NOT NULL,
PRIMARY KEY (NSMD_INSTRU_ID, NSMD_MODAL_ID),
CONSTRAINT NSMD_PKFK_INSTRU_ID FOREIGN KEY (NSMD_INSTRU_ID) REFERENCES INSTRUTORES(INSTRU_ID),
CONSTRAINT NSMD_PKFK_MODAL_ID FOREIGN KEY (NSMD_MODAL_ID) REFERENCES MODALIDADES(MODAL_ID)
);

ALTER TABLE INSTRUTORES_MODALIDADES ADD NSMD_QUANTIDADE VARCHAR(100);
ALTER TABLE INSTRUTORES_MODALIDADES MODIFY COLUMN NSMD_QUANTIDADE INT;
ALTER TABLE INSTRUTORES_MODALIDADES CHANGE COLUMN NSMD_QUANTIDADE NSMD_QT INT;
ALTER TABLE INSTRUTORES_MODALIDADES DROP COLUMN NSMD_QT;

CREATE TABLE IF NOT EXISTS PLANOS_DE_TREINO(
PDT_ID INT PRIMARY KEY NOT NULL,
PDT_ALU_ID INT NOT NULL,
PDT_NSMD_INSTRU_ID INT NOT NULL,
PDT_NSMD_MODAL_ID INT NOT NULL,
CONSTRAINT FK_PDT_ALU_ID FOREIGN KEY (PDT_ALU_ID) REFERENCES ALUNOS(ALU_ID),
CONSTRAINT FK_PDT_NSMD_INSTRU_ID FOREIGN KEY (PDT_NSMD_INSTRU_ID) REFERENCES INSTRUTORES_MODALIDADES(NSMD_INSTRU_ID),
CONSTRAINT FK_PDT_NSMD_MODAL_ID FOREIGN KEY (PDT_NSMD_MODAL_ID) REFERENCES INSTRUTORES_MODALIDADES(NSMD_MODAL_ID)
);

ALTER TABLE PLANOS_DE_TREINO ADD PDT_QUANTIDADE VARCHAR(100);
ALTER TABLE PLANOS_DE_TREINO MODIFY COLUMN PDT_QUANTIDADE INT;
ALTER TABLE PLANOS_DE_TREINO CHANGE COLUMN PDT_QUANTIDADE PDT_QT INT;
ALTER TABLE PLANOS_DE_TREINO DROP COLUMN PDT_QT;

CREATE TABLE IF NOT EXISTS AULAS(
AUL_ID INT PRIMARY KEY NOT NULL,
AUL_HORARIO TIME NOT NULL,
AUL_CAPACIADE INT NOT NULL,
AUL_NSMD_INSTRU_ID INT NOT NULL,
AUL_NSMD_MODAL_ID INT NOT NULL,
AUL_PDT_ID INT NOT NULL,
CONSTRAINT FK_AUL_NSMD_INSTRU_ID FOREIGN KEY (AUL_NSMD_INSTRU_ID) REFERENCES INSTRUTORES_MODALIDADES(NSMD_INSTRU_ID),
CONSTRAINT FK_AUL_NSMD_MODAL_ID FOREIGN KEY (AUL_NSMD_MODAL_ID) REFERENCES INSTRUTORES_MODALIDADES(NSMD_MODAL_ID),
CONSTRAINT FK_AUL_PDT_ID FOREIGN KEY (AUL_PDT_ID) REFERENCES PLANOS_DE_TREINO(PDT_ID)
);

ALTER TABLE AULAS ADD AUL_QUANTIDADE VARCHAR(100);
ALTER TABLE AULAS MODIFY COLUMN AUL_QUANTIDADE INT;
ALTER TABLE AULAS CHANGE COLUMN AUL_QUANTIDADE AUL_QT INT;
ALTER TABLE AULAS DROP COLUMN AUL_QT;
